<?php

/**
 * @package  RCF Req Plugin
 */

namespace Inc\Base;

/**
 * 
 */
class AddAcfFields
{
	public function register()
	{
		if (function_exists('acf_add_local_field_group')) {

			acf_add_local_field_group(array(
				'key' => 'Req_group',
				'title' => 'Requirement manager',
				'fields' => array(
					// array(
					// 	'key' => 'field_requirement_info',
					// 	'label' => 'Requirement Info',
					// 	'name' => 'requirement_info',
					// 	'type' => 'group',
					// 	'instructions' => '',
					// 	'required' => 0,
					// 	'conditional_logic' => 0,
					// 	'wrapper' => array(
					// 		'width' => '',
					// 		'class' => '',
					// 		'id' => '',
					// 	),
					// 	'layout' => 'table',
					// 	'sub_fields' => array(
					// 		array(
					// 			'key' => 'field_req_key',
					// 			'label' => 'Requirement Key',
					// 			'name' => 'req_key',
					// 			'type' => 'taxonomy',
					// 			'instructions' => '',
					// 			'required' => 0,
					// 			'conditional_logic' => 0,
					// 			'wrapper' => array(
					// 				'width' => '',
					// 				'class' => '',
					// 				'id' => '',
					// 			),
					// 			'taxonomy' => 'req_key',
					// 			'field_type' => 'select',
					// 			'allow_null' => 0,
					// 			'add_term' => 1,
					// 			'save_terms' => 1,
					// 			'load_terms' => 1,
					// 			'return_format' => 'object',
					// 			'multiple' => 0,
					// 		),
					// 		array(
					// 			'key' => 'field_league',
					// 			'label' => 'League',
					// 			'name' => 'league',
					// 			'type' => 'taxonomy',
					// 			'instructions' => '',
					// 			'required' => 0,
					// 			'conditional_logic' => 0,
					// 			'wrapper' => array(
					// 				'width' => '',
					// 				'class' => '',
					// 				'id' => '',
					// 			),
					// 			'taxonomy' => 'league',
					// 			'field_type' => 'select',
					// 			'allow_null' => 0,
					// 			'add_term' => 1,
					// 			'save_terms' => 1,
					// 			'load_terms' => 1,
					// 			'return_format' => 'id',
					// 			'multiple' => 0,
					// 		),
					// 	),
					// ),
					array(
						'key' => 'field_5f845c52e9e3e',
						'label' => 'Participation Info',
						'name' => 'participation_info',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'sub_fields' => array(
							array(
								'key' => 'field_5f845d98ac217',
								'label' => 'Qualified teams count',
								'name' => 'qualified_teams_count',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 1,
								'max' => 30,
								'step' => '',
							),
							array(
								'key' => 'field_5f845dc6ac218',
								'label' => 'Registered teams count',
								'name' => 'registered_teams_count_',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 1,
								'max' => 30,
								'step' => '',
							),
							array(
								'key' => 'field_5f845dddac219',
								'label' => 'Participated teams count',
								'name' => 'participated_teams_count',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 1,
								'max' => 30,
								'step' => '',
							),
						),
					),
					array(
						'key' => 'field_5f9fed4fe06db',
						'label' => 'Competition Area',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5f845e7ccb62f',
						'label' => 'Field Info',
						'name' => 'field_info',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'sub_fields' => array(
							array(
								'key' => 'field_5f845e91cb630',
								'label' => 'Number of Fields',
								'name' => 'number_of_fields',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 1,
								'max' => 5,
								'step' => '',
							),
							array(
								'key' => 'field_5f845eabcb631',
								'label' => 'Gross space per field (sqm)',
								'name' => 'gross_space_per_field',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 1,
								'max' => 100,
								'step' => '',
							),
							array(
								'key' => 'field_5f845ed3cb632',
								'label' => 'Total space (sqm)',
								'name' => 'total_space_sqm',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 1,
								'max' => 200,
								'step' => '',
							),
						),
					),
					array(
						'key' => 'field_5f822cb91be38',
						'label' => 'Detailed setup',
						'name' => 'detailed_setup',
						'type' => 'wysiwyg',
						'instructions' => 'Detailed setup requirements per physical field (geometric layout, type of material, WLAN, PCs/notebooks for game controllers, table(s) at fields for teams/referees, …) or per virtual fields (competition infrastructure for simulation leagues)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'visual',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f822cfe1be39',
						'label' => 'Environment requirements',
						'name' => 'environment_requirements',
						'type' => 'wysiwyg',
						'instructions' => 'Environment requirements for fields (e.g. lightning, protection walls/net, special WLAN/LAN)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f822dabb4e1b',
						'label' => 'Best practices',
						'name' => 'best_practices',
						'type' => 'wysiwyg',
						'instructions' => 'Comments and best practices for the effective setup of fields',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'default_value' => '',
						'delay' => 0,
					),
					array(
						'key' => 'field_5f822dd4b4e1c',
						'label' => 'Additional equipments',
						'name' => 'additional_equipments',
						'type' => 'wysiwyg',
						'instructions' => 'Additional (mobile) equipment needed (like balls for games or other stuff for the technical challenge)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f9fede9e06dc',
						'label' => 'League Organization Area',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5f822dfbb4e1d',
						'label' => 'OC Requirments',
						'name' => 'oc_requirments',
						'type' => 'wysiwyg',
						'instructions' => 'OC requirements (OC table, further material)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f9fee05e06dd',
						'label' => 'Teams Area',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5f822e1db4e1e',
						'label' => 'Participation Area',
						'name' => 'participation_area',
						'type' => 'wysiwyg',
						'instructions' => 'Participant area requirements (team area)
Does the league contain real robots? Recommended average additional free space for teams (needed to handle the robots)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f9fee22e06de',
						'label' => 'Others',
						'name' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5f822f0fb4e20',
						'label' => 'New Changes',
						'name' => 'new_changes',
						'type' => 'wysiwyg',
						'instructions' => 'describe any relevant changes compared to last year 
(Note: Significant changes require trustee’s approval)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f822f32b4e21',
						'label' => 'Additional Information',
						'name' => 'additional_information',
						'type' => 'wysiwyg',
						'instructions' => '(i.e. outdoor events; extra requirements; etc)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_5f822f5cb4e22',
						'label' => 'OC & TC internal field',
						'name' => 'oc_tc_internal_field',
						'type' => 'wysiwyg',
						'instructions' => 'Sharing best practices from one year to the next year between OCs',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_status',
							'operator' => '==',
							'value' => 'auto-draft',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'requirement',
						),
					),
					array(
						array(
							'param' => 'post_status',
							'operator' => '==',
							'value' => 'ec',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'requirement',
						),
					),
					array(
						array(
							'param' => 'post_status',
							'operator' => '==',
							'value' => 'trustee',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'requirement',
						),
					),
					array(
						array(
							'param' => 'post_status',
							'operator' => '==',
							'value' => 'loc',
						),
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'requirement',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'acf_after_title',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'slug',
					6 => 'author',
					7 => 'format',
					8 => 'page_attributes',
					9 => 'featured_image',
					10 => 'categories',
					11 => 'tags',
					12 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
			));
		}
	}
}
